#!/bin/sh

# Mount /proc and /sys
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts devpts /dev/pts

# Disable kernel messages
echo 0 > /proc/sys/kernel/printk

# Start mdev to populate /dev
mdev -s

# Optain IP address
ip link set eth0 up
udhcpc -b -i eth0 -s /etc/udhcpc/default.script

# Enable multicast
ip route add 224.0.0.0/4 dev eth0

# Starting ssh server
/usr/sbin/dropbear -E
