#!/bin/sh

# Create identifier file
touch /etc/maintenance

# Create the info pipe
mkfifo /var/run/info

# Mount /proc and /sys
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts devpts /dev/pts

# Start syslog server
/sbin/syslogd -C4096

# Disable kernel messages
echo 0 > /proc/sys/kernel/printk

# Start mdev to populate /dev
mdev -s

# Optain IP address
ip link set eth0 up
udhcpc -S -b -i eth0 -s /etc/udhcpc/default.script

# Enable multicast
ip route add 224.0.0.0/4 dev eth0

# Enable multicast ping
echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

# Starting ssh server
PATH="/sbin:/usr/sbin:$PATH" /usr/sbin/dropbear -s
